name: agrosnap
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  introduction_screen: ^2.1.0
  provider: ^6.0.1
  share: ^2.0.4
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  image_picker: ^0.8.4+8
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.5.2
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.1.3
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  flutter_native_timezone: ^2.0.0
  cached_network_image: ^3.2.0
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - Assets/intro1.png
    - Assets/intro2.png
    - Assets/intro3.png
    - Assets/intro4.png
    - Assets/palm.png
    - Assets/store.png
    - Assets/plantCare.png
    - Assets/withered.png
    - Assets/plant.png
    - Assets/wheat.png
    - Assets/flower.png
    - Assets/harvest.png
    - Assets/seed.png
    - Assets/background.png
    - Assets/fruits.png
    - Assets/polygon.png
    - Assets/overview.png
    - Assets/heat.png
    - Assets/image3.png
    - Assets/image4.png
    - Assets/image6.png
    - Assets/image7.png
    - Assets/image8.png
    - Assets/image9.png
    - Assets/image11.png
    - Assets/image12.png
    - Assets/disease.png
    - Assets/flask(1).png
    - Assets/herbal-treatment.png
    - Assets/save-nature.png
    - Assets/virus.png